# Generated by Django 5.1.3 on 2025-03-04 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codemodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursesmodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.teachersmodel'),
        ),
        migrations.AlterField(
            model_name='coursesmodel',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.yearsmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='courses.majorsmodel'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='courses.yearsmodel'),
        ),
    ]
